create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text,
    display_name text,
    native_language text default 'ru',
    preferred_explanation_language text default 'en',
    cefr_level text not null default 'B1'
        check (cefr_level in ('A1','A2','B1','B2','C1','C2')),
    learning_goal text,
    target_level text
        check (target_level is null or target_level in ('A1','A2','B1','B2','C1','C2')),
    daily_goal_minutes integer not null default 20
        check (daily_goal_minutes between 5 and 300),
    timezone text default 'Asia/Oral',
    onboarding_completed boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.learning_sessions (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    session_type text not null check (session_type in (
        'tutor','grammar','vocabulary','writing','speaking',
        'reading','listening','test','mixed'
    )),
    title text,
    started_at timestamptz not null default now(),
    ended_at timestamptz,
    duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
    score integer check (score is null or score between 0 and 100),
    cefr_level text check (cefr_level is null or cefr_level in ('A1','A2','B1','B2','C1','C2')),
    metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.student_skills (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    category text not null check (category in (
        'grammar','vocabulary','writing','speaking','reading','listening'
    )),
    skill text not null,
    score integer not null default 50 check (score between 0 and 100),
    level text not null default 'B1'
        check (level in ('A1','A2','B1','B2','C1','C2')),
    attempts integer not null default 0,
    correct_answers integer not null default 0,
    total_answers integer not null default 0,
    confidence numeric(5,2) not null default 0 check (confidence between 0 and 100),
    last_practiced timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(user_id, category)
);

create table if not exists public.skill_mastery (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    category text not null,
    skill_code text not null,
    skill_name text not null,
    score integer not null default 50 check (score between 0 and 100),
    attempts integer not null default 0,
    successes integer not null default 0,
    last_error text,
    last_practiced timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(user_id, skill_code)
);

create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    session_id uuid references public.learning_sessions(id) on delete set null,
    role text not null check (role in ('user','assistant','system')),
    content text not null,
    mode text default 'tutor',
    created_at timestamptz not null default now()
);

create table if not exists public.learning_events (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    session_id uuid references public.learning_sessions(id) on delete set null,
    activity_type text not null,
    topic text not null,
    score integer check (score is null or score between 0 and 100),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.grammar_errors (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    session_id uuid references public.learning_sessions(id) on delete set null,
    source_text text,
    original_fragment text not null,
    corrected_fragment text not null,
    rule_name text,
    explanation text,
    severity text default 'medium' check (severity in ('low','medium','high')),
    resolved boolean not null default false,
    created_at timestamptz not null default now(),
    resolved_at timestamptz
);

create table if not exists public.vocabulary_words (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    word text not null,
    lemma text,
    part_of_speech text,
    definition text,
    translation text,
    example_sentence text,
    collocation text,
    topic text,
    cefr_level text check (cefr_level is null or cefr_level in ('A1','A2','B1','B2','C1','C2')),
    status text not null default 'learning'
        check (status in ('new','learning','review','mastered')),
    ease_factor numeric(4,2) not null default 2.50,
    interval_days integer not null default 0,
    repetitions integer not null default 0,
    correct_count integer not null default 0,
    wrong_count integer not null default 0,
    last_reviewed_at timestamptz,
    next_review_at timestamptz,
    created_at timestamptz not null default now(),
    unique(user_id, word)
);

create table if not exists public.vocabulary_reviews (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    vocabulary_id uuid not null references public.vocabulary_words(id) on delete cascade,
    quality integer not null check (quality between 0 and 5),
    correct boolean not null,
    response text,
    reviewed_at timestamptz not null default now()
);

create table if not exists public.tests (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references auth.users(id) on delete cascade,
    title text not null,
    test_type text not null default 'adaptive',
    focus text not null default 'mixed',
    level text check (level is null or level in ('A1','A2','B1','B2','C1','C2')),
    questions jsonb not null,
    created_at timestamptz not null default now()
);

create table if not exists public.test_attempts (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    test_id uuid references public.tests(id) on delete set null,
    title text,
    level text check (level is null or level in ('A1','A2','B1','B2','C1','C2')),
    focus text,
    score integer check (score between 0 and 100),
    correct_count integer not null default 0,
    total_count integer not null default 0,
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.test_answers (
    id uuid primary key default gen_random_uuid(),
    attempt_id uuid not null references public.test_attempts(id) on delete cascade,
    question_number integer not null,
    skill text,
    question text not null,
    selected_answer text,
    correct_answer text,
    is_correct boolean not null,
    explanation text,
    created_at timestamptz not null default now()
);

create table if not exists public.writing_attempts (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    session_id uuid references public.learning_sessions(id) on delete set null,
    purpose text not null default 'general',
    prompt text,
    original_text text not null,
    revised_text text,
    score integer check (score between 0 and 100),
    estimated_level text check (
        estimated_level is null or estimated_level in ('A1','A2','B1','B2','C1','C2')
    ),
    grammar_score integer check (grammar_score is null or grammar_score between 0 and 100),
    vocabulary_score integer check (vocabulary_score is null or vocabulary_score between 0 and 100),
    coherence_score integer check (coherence_score is null or coherence_score between 0 and 100),
    organization_score integer check (organization_score is null or organization_score between 0 and 100),
    feedback jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.speaking_attempts (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    session_id uuid references public.learning_sessions(id) on delete set null,
    scenario text not null,
    transcript text not null,
    score integer check (score is null or score between 0 and 100),
    estimated_level text check (
        estimated_level is null or estimated_level in ('A1','A2','B1','B2','C1','C2')
    ),
    fluency_score integer check (fluency_score is null or fluency_score between 0 and 100),
    vocabulary_score integer check (vocabulary_score is null or vocabulary_score between 0 and 100),
    grammar_score integer check (grammar_score is null or grammar_score between 0 and 100),
    pronunciation_score integer,
    feedback jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

comment on column public.speaking_attempts.pronunciation_score is
'Populate only when acoustic audio analysis is available; do not infer pronunciation from transcript.';

create table if not exists public.reading_attempts (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    title text,
    source_text text,
    source_url text,
    level text check (level is null or level in ('A1','A2','B1','B2','C1','C2')),
    score integer check (score is null or score between 0 and 100),
    questions jsonb not null default '[]'::jsonb,
    answers jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.listening_attempts (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    title text,
    audio_url text,
    transcript text,
    level text check (level is null or level in ('A1','A2','B1','B2','C1','C2')),
    score integer check (score is null or score between 0 and 100),
    questions jsonb not null default '[]'::jsonb,
    answers jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.recommendations (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    category text not null,
    title text not null,
    reason text,
    priority integer not null default 3 check (priority between 1 and 5),
    status text not null default 'active'
        check (status in ('active','completed','dismissed','expired')),
    action_type text,
    action_payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    completed_at timestamptz,
    expires_at timestamptz
);

create table if not exists public.learning_goals (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    title text not null,
    description text,
    goal_type text not null default 'skill',
    target_value numeric,
    current_value numeric not null default 0,
    unit text,
    target_date date,
    status text not null default 'active'
        check (status in ('active','completed','paused','cancelled')),
    created_at timestamptz not null default now(),
    completed_at timestamptz
);

create table if not exists public.daily_progress (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    progress_date date not null default current_date,
    minutes_studied integer not null default 0,
    activities_completed integer not null default 0,
    questions_answered integer not null default 0,
    correct_answers integer not null default 0,
    xp integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(user_id, progress_date)
);

create table if not exists public.achievements (
    id uuid primary key default gen_random_uuid(),
    code text not null unique,
    name text not null,
    description text,
    icon text,
    xp_reward integer not null default 0,
    criteria jsonb not null default '{}'::jsonb
);

create table if not exists public.user_achievements (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    achievement_id uuid not null references public.achievements(id) on delete cascade,
    earned_at timestamptz not null default now(),
    unique(user_id, achievement_id)
);

create index if not exists idx_sessions_user_started on public.learning_sessions(user_id, started_at desc);
create index if not exists idx_skills_user on public.student_skills(user_id);
create index if not exists idx_mastery_user on public.skill_mastery(user_id, category, score);
create index if not exists idx_messages_user_created on public.messages(user_id, created_at desc);
create index if not exists idx_events_user_created on public.learning_events(user_id, created_at desc);
create index if not exists idx_errors_user on public.grammar_errors(user_id, resolved, created_at desc);
create index if not exists idx_vocab_due on public.vocabulary_words(user_id, status, next_review_at);
create index if not exists idx_test_attempts_user on public.test_attempts(user_id, completed_at desc);
create index if not exists idx_writing_user on public.writing_attempts(user_id, created_at desc);
create index if not exists idx_speaking_user on public.speaking_attempts(user_id, created_at desc);
create index if not exists idx_recommendations_user on public.recommendations(user_id, status, priority);
create index if not exists idx_goals_user on public.learning_goals(user_id, status);
create index if not exists idx_daily_user on public.daily_progress(user_id, progress_date desc);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_student_skills_updated_at on public.student_skills;
create trigger trg_student_skills_updated_at
before update on public.student_skills
for each row execute function public.set_updated_at();

drop trigger if exists trg_skill_mastery_updated_at on public.skill_mastery;
create trigger trg_skill_mastery_updated_at
before update on public.skill_mastery
for each row execute function public.set_updated_at();

drop trigger if exists trg_daily_progress_updated_at on public.daily_progress;
create trigger trg_daily_progress_updated_at
before update on public.daily_progress
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, email, display_name)
    values (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.learning_sessions enable row level security;
alter table public.student_skills enable row level security;
alter table public.skill_mastery enable row level security;
alter table public.messages enable row level security;
alter table public.learning_events enable row level security;
alter table public.grammar_errors enable row level security;
alter table public.vocabulary_words enable row level security;
alter table public.vocabulary_reviews enable row level security;
alter table public.tests enable row level security;
alter table public.test_attempts enable row level security;
alter table public.test_answers enable row level security;
alter table public.writing_attempts enable row level security;
alter table public.speaking_attempts enable row level security;
alter table public.reading_attempts enable row level security;
alter table public.listening_attempts enable row level security;
alter table public.recommendations enable row level security;
alter table public.learning_goals enable row level security;
alter table public.daily_progress enable row level security;
alter table public.achievements enable row level security;
alter table public.user_achievements enable row level security;

drop policy if exists "profiles own select" on public.profiles;
create policy "profiles own select" on public.profiles
for select to authenticated using (auth.uid() = id);

drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles
for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

do $$
declare
    t text;
begin
    foreach t in array array[
        'learning_sessions','student_skills','skill_mastery','messages',
        'learning_events','grammar_errors','vocabulary_words','vocabulary_reviews',
        'test_attempts','writing_attempts','speaking_attempts','reading_attempts',
        'listening_attempts','recommendations','learning_goals','daily_progress',
        'user_achievements'
    ]
    loop
        execute format('drop policy if exists "own select" on public.%I', t);
        execute format('create policy "own select" on public.%I for select to authenticated using (auth.uid() = user_id)', t);
        execute format('drop policy if exists "own insert" on public.%I', t);
        execute format('create policy "own insert" on public.%I for insert to authenticated with check (auth.uid() = user_id)', t);
        execute format('drop policy if exists "own update" on public.%I', t);
        execute format('create policy "own update" on public.%I for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id)', t);
        execute format('drop policy if exists "own delete" on public.%I', t);
        execute format('create policy "own delete" on public.%I for delete to authenticated using (auth.uid() = user_id)', t);
    end loop;
end $$;

drop policy if exists "tests own select" on public.tests;
create policy "tests own select" on public.tests
for select to authenticated using (user_id is null or auth.uid() = user_id);

drop policy if exists "tests own insert" on public.tests;
create policy "tests own insert" on public.tests
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "test answers own select" on public.test_answers;
create policy "test answers own select" on public.test_answers
for select to authenticated
using (
    exists (
        select 1 from public.test_attempts a
        where a.id = attempt_id and a.user_id = auth.uid()
    )
);

drop policy if exists "test answers own insert" on public.test_answers;
create policy "test answers own insert" on public.test_answers
for insert to authenticated
with check (
    exists (
        select 1 from public.test_attempts a
        where a.id = attempt_id and a.user_id = auth.uid()
    )
);

drop policy if exists "achievements read" on public.achievements;
create policy "achievements read" on public.achievements
for select to authenticated using (true);

insert into public.achievements (code, name, description, icon, xp_reward, criteria)
values
    ('FIRST_LESSON','First Step','Complete your first learning activity.','🎯',20,'{"activities":1}'),
    ('TEN_ACTIVITIES','Keep Going','Complete 10 learning activities.','🔥',50,'{"activities":10}'),
    ('VOCAB_25','Word Collector','Add 25 words to your vocabulary bank.','📚',50,'{"vocabulary":25}'),
    ('STREAK_7','Seven Day Streak','Study on 7 consecutive days.','⚡',100,'{"streak_days":7}')
on conflict (code) do nothing;

create or replace view public.v_student_progress as
select
    p.id as user_id,
    p.display_name,
    p.cefr_level,
    p.target_level,
    coalesce((select avg(ss.score) from public.student_skills ss where ss.user_id = p.id), 0)::numeric(5,2) as average_skill_score,
    (select count(*) from public.learning_events le where le.user_id = p.id) as total_activities,
    (select count(*) from public.test_attempts ta where ta.user_id = p.id) as total_tests,
    (select count(*) from public.writing_attempts wa where wa.user_id = p.id) as total_writing_attempts,
    (select count(*) from public.speaking_attempts sa where sa.user_id = p.id) as total_speaking_attempts,
    (select count(*) from public.vocabulary_words vw where vw.user_id = p.id) as vocabulary_size
from public.profiles p;

-- ============================================================
-- IELTS EXTENSION FOR AI ENGLISH TUTOR
-- Safe additive migration for an existing full project schema.
-- Run this file if the General English schema already exists.
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.ielts_profiles (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null unique references auth.users(id) on delete cascade,
    exam_type text not null default 'Academic'
        check (exam_type in ('Academic','General Training')),
    target_band numeric(2,1) not null default 6.5
        check (target_band between 1 and 9),
    planned_exam_date date,
    current_overall_band numeric(2,1)
        check (current_overall_band is null or current_overall_band between 0 and 9),
    listening_band numeric(2,1)
        check (listening_band is null or listening_band between 0 and 9),
    reading_band numeric(2,1)
        check (reading_band is null or reading_band between 0 and 9),
    writing_band numeric(2,1)
        check (writing_band is null or writing_band between 0 and 9),
    speaking_band numeric(2,1)
        check (speaking_band is null or speaking_band between 0 and 9),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.ielts_writing_attempts (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    test_type text not null default 'Academic'
        check (test_type in ('Academic','General Training')),
    task_number integer not null check (task_number in (1,2)),
    prompt text not null,
    response_text text not null,
    word_count integer,
    task_score numeric(2,1) check (task_score is null or task_score between 0 and 9),
    coherence_cohesion numeric(2,1) check (coherence_cohesion is null or coherence_cohesion between 0 and 9),
    lexical_resource numeric(2,1) check (lexical_resource is null or lexical_resource between 0 and 9),
    grammatical_range_accuracy numeric(2,1) check (grammatical_range_accuracy is null or grammatical_range_accuracy between 0 and 9),
    estimated_band numeric(2,1) check (estimated_band is null or estimated_band between 0 and 9),
    feedback jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.ielts_speaking_attempts (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    part integer not null check (part between 1 and 3),
    prompt text not null,
    transcript text not null,
    fluency_coherence numeric(2,1) check (fluency_coherence is null or fluency_coherence between 0 and 9),
    lexical_resource numeric(2,1) check (lexical_resource is null or lexical_resource between 0 and 9),
    grammatical_range_accuracy numeric(2,1) check (grammatical_range_accuracy is null or grammatical_range_accuracy between 0 and 9),
    pronunciation numeric(2,1) check (pronunciation is null or pronunciation between 0 and 9),
    provisional_language_band numeric(2,1) check (provisional_language_band is null or provisional_language_band between 0 and 9),
    feedback jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

comment on column public.ielts_speaking_attempts.pronunciation is
'Leave NULL for transcript-only assessment. Populate only when a valid acoustic pronunciation assessment is implemented.';

create table if not exists public.ielts_objective_attempts (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    section text not null check (section in ('reading','listening')),
    test_type text not null default 'Academic'
        check (test_type in ('Academic','General Training')),
    title text not null,
    score_percent integer not null check (score_percent between 0 and 100),
    estimated_band numeric(2,1) check (estimated_band is null or estimated_band between 0 and 9),
    answers jsonb not null default '{}'::jsonb,
    details jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.ielts_band_history (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    section text not null check (section in ('listening','reading','writing','speaking','overall')),
    band numeric(2,1) not null check (band between 0 and 9),
    source text not null default 'ai_practice_estimate',
    note text,
    created_at timestamptz not null default now()
);

create table if not exists public.ielts_mock_tests (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    test_type text not null default 'Academic'
        check (test_type in ('Academic','General Training')),
    status text not null default 'in_progress'
        check (status in ('in_progress','completed','abandoned')),
    listening_band numeric(2,1),
    reading_band numeric(2,1),
    writing_band numeric(2,1),
    speaking_band numeric(2,1),
    overall_band numeric(2,1),
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_ielts_writing_user_created
on public.ielts_writing_attempts(user_id, created_at desc);

create index if not exists idx_ielts_speaking_user_created
on public.ielts_speaking_attempts(user_id, created_at desc);

create index if not exists idx_ielts_objective_user_section
on public.ielts_objective_attempts(user_id, section, created_at desc);

create index if not exists idx_ielts_band_history_user
on public.ielts_band_history(user_id, created_at desc);

create index if not exists idx_ielts_mock_user
on public.ielts_mock_tests(user_id, started_at desc);

alter table public.ielts_profiles enable row level security;
alter table public.ielts_writing_attempts enable row level security;
alter table public.ielts_speaking_attempts enable row level security;
alter table public.ielts_objective_attempts enable row level security;
alter table public.ielts_band_history enable row level security;
alter table public.ielts_mock_tests enable row level security;

do $$
declare
    t text;
begin
    foreach t in array array[
        'ielts_profiles','ielts_writing_attempts','ielts_speaking_attempts',
        'ielts_objective_attempts','ielts_band_history','ielts_mock_tests'
    ]
    loop
        execute format('drop policy if exists "ielts own select" on public.%I', t);
        execute format('create policy "ielts own select" on public.%I for select to authenticated using (auth.uid() = user_id)', t);
        execute format('drop policy if exists "ielts own insert" on public.%I', t);
        execute format('create policy "ielts own insert" on public.%I for insert to authenticated with check (auth.uid() = user_id)', t);
        execute format('drop policy if exists "ielts own update" on public.%I', t);
        execute format('create policy "ielts own update" on public.%I for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id)', t);
        execute format('drop policy if exists "ielts own delete" on public.%I', t);
        execute format('create policy "ielts own delete" on public.%I for delete to authenticated using (auth.uid() = user_id)', t);
    end loop;
end $$;



-- ============================================================
-- FULL IELTS MOCK EXAM EXTENSION
-- Additive migration. Run after the existing IELTS schema.
-- ============================================================

create table if not exists public.ielts_mock_sections (
    id uuid primary key default gen_random_uuid(),
    mock_id uuid not null references public.ielts_mock_tests(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    section text not null check (section in ('listening','reading','writing','speaking')),
    part integer not null check (part between 1 and 4),
    status text not null default 'ready'
        check (status in ('ready','in_progress','completed')),
    content jsonb not null default '{}'::jsonb,
    answers jsonb not null default '{}'::jsonb,
    result jsonb not null default '{}'::jsonb,
    raw_score integer,
    total_questions integer,
    estimated_band numeric(2,1)
        check (estimated_band is null or estimated_band between 0 and 9),
    started_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    unique(mock_id, section, part)
);

create index if not exists idx_ielts_mock_sections_mock
on public.ielts_mock_sections(mock_id, section, part);

create index if not exists idx_ielts_mock_sections_user
on public.ielts_mock_sections(user_id, created_at desc);

alter table public.ielts_mock_sections enable row level security;

drop policy if exists "ielts mock sections own select" on public.ielts_mock_sections;
create policy "ielts mock sections own select"
on public.ielts_mock_sections for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "ielts mock sections own insert" on public.ielts_mock_sections;
create policy "ielts mock sections own insert"
on public.ielts_mock_sections for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "ielts mock sections own update" on public.ielts_mock_sections;
create policy "ielts mock sections own update"
on public.ielts_mock_sections for update to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "ielts mock sections own delete" on public.ielts_mock_sections;
create policy "ielts mock sections own delete"
on public.ielts_mock_sections for delete to authenticated
using (auth.uid() = user_id);
