-- Run this entire file in Supabase -> SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  cefr_level text not null default 'B1'
    check (cefr_level in ('A1','A2','B1','B2','C1','C2')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.student_skills (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null check (category in ('grammar','vocabulary','writing','speaking','reading','listening')),
  skill text not null,
  score integer not null default 50 check (score between 0 and 100),
  level text not null default 'B1' check (level in ('A1','A2','B1','B2','C1','C2')),
  attempts integer not null default 0,
  last_practiced timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id, category)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.learning_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_type text not null,
  topic text not null,
  score integer check (score between 0 and 100),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_messages_user_created
  on public.messages(user_id, created_at desc);

create index if not exists idx_learning_events_user_created
  on public.learning_events(user_id, created_at desc);

-- Enable RLS. The application uses a server-only service-role key for its DB operations.
alter table public.profiles enable row level security;
alter table public.student_skills enable row level security;
alter table public.messages enable row level security;
alter table public.learning_events enable row level security;

-- These policies also allow authenticated users to read only their own rows if
-- you later choose to query Supabase directly from the browser.
drop policy if exists "profiles read own" on public.profiles;
create policy "profiles read own" on public.profiles for select
  to authenticated using ((select auth.uid()) = id);

drop policy if exists "skills read own" on public.student_skills;
create policy "skills read own" on public.student_skills for select
  to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "messages read own" on public.messages;
create policy "messages read own" on public.messages for select
  to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "events read own" on public.learning_events;
create policy "events read own" on public.learning_events for select
  to authenticated using ((select auth.uid()) = user_id);
